website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Note(db.Model): #ejemplo
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(1000))
    date = db.Column(db.DateTime(timezone=True), default=func.now()) # Recopila la fecha automaticamente
    user_id = db.Column(db.Integer, db.ForeignKey('user.id')) # Conectar dos tablas 

class User(db.Model, UserMixin): #Definir las tablas de usuario, practicamente lo mismo que tenemos en sql
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    direccion = db.Column(db.String(150)) 
    notes = db.relationship('Note')

#Libros
class Libro(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    titulo = db.Column(db.String(150), unique=True)
    autor =  db.Column(db.String(150))
    ISBN =  db.Column(db.String(150))
    desc =  db.Column(db.String(150))
    precio = db.Column(db.Integer)
    stock = db.Column(db.Integer)
    Imagen=db.Column(db.Text)

#Pedidos
class Pedido(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    libro_id = db.Column(db.Integer, db.ForeignKey('libro.id'))
    cant = db.Column(db.Integer)
    estado = db.Column(db.String(150))
    paqueteria_id = db.Column(db.Integer, db.ForeignKey('paqueteria.id'))
    precio_libro = db.Column(db.Integer)
    precio_envio = db.Column(db.Integer)

#Paqueteria
class Paqueteria(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nombre_paqueteria = db.Column(db.String(150))
    tarifa = db.Column(db.Integer)

#Proveedor
class Proveedor(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nombre_proveedor = db.Column(db.String(150))
    dir_proveedor = db.Column(db.String(150)) 
    email_proveedor = db.Column(db.String(150), unique=True)
    
    

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'qwerty'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}' # DATABASE LOCATION
    db.init_app(app)

    

    from .views import views #importar los files
    from .auth import auth

    app.register_blueprint(views, url_prefix='/') #registrar los blueprints
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request,flash,redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from .models import User
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__ )

@auth.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Has iniciado sesion', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Contraseña incorrecta', category='error')
        else:
            flash('Email no existe', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login')) 

@auth.route('/sign-up', methods=['GET','POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        direccion = request.form.get('direccion')
        password1 = request.form.get('password1')
        
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email ya existe', category='error')
        elif len(email) < 4:
            flash('Email demasiado pequeño', category='error')
        elif len(first_name) < 2:
            flash('Nombre no valido', category='error')
        elif len(direccion) < 4:
            flash('Direccion demasido corta, no valido', category='error')
        elif len(password1) < 7:
            flash('Contraseña no valida(demasiado corta)', category='error')
        else:
            new_user = User(email = email, first_name=first_name, direccion=direccion, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Cuenta creada', category='success')
            return redirect(url_for('views.home'))
    return render_template("sign_up.html", user=current_user) 

website/views.py
from flask import Blueprint,render_template, request, redirect, url_for
from flask_login import login_required, current_user
from .models import Libro
from .models import Pedido
views = Blueprint('views', __name__ )

@views.route('/')
def home():
    libros = Libro.query.limit(10).all()
    return render_template("home.html", user=current_user,libros=libros)

@views.route('/seguimiento')
def seguimiento():
    # Obtén los pedidos de la base de datos, por ejemplo, si estás utilizando SQLAlchemy
    pedidos = Pedido.query.all()
    
    return render_template("seguimiento.html", user=current_user, pedidos=pedidos)



@views.route('/detalle_Libro/<int:id_libro>')
def detalle(id_libro):
    libro = Libro.query.get(id_libro)
    return render_template("detalle_libro.html", user=current_user,libro=libro)

@views.route('/carrito')
def carritoCompras():
    return render_template("pagos.html",user=current_user)

@views.route('/pagar', methods=['POST'])
def pagar():
    # Procesamiento del formulario
    return redirect(url_for('views.home'))

@views.route('/buscar', methods=['GET', 'POST'])
def buscar():
    if request.method == 'POST':
        titulo = request.form.get('titulo')
        # Ahora puedes usar 'titulo' para hacer una búsqueda en tu base de datos, por ejemplo.
        libros_encontrados = Libro.query.filter(Libro.titulo.ilike(f'%{titulo}%')).all()
        return render_template('buscar.html', user=current_user,libros=libros_encontrados)
    return render_template('home.html')

@views.route('/altas_libros')
def altas():
    return render_template('alta_libros.html',user=current_user)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- AQUI ESTAN TODOS LOS LINKS A CSS Y AGREGUE UN BLOQUE LINK PARA PONER UN CSS PERSONALIZADO-->
    <link 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block link %}{% endblock %}
    <!-- estilo del footer-->
    <style>
      /* Estilo para el pie de página */
      footer {
          margin-top: auto;  /* Empujar el footer hacia abajo */
          bottom: 0;
          width: 100%;
      }
  </style>

    <!-- AQUI ESTA EL TITULO DE LA PAGINA-->
    <title>{% block title%}{% endblock %}</title>
</head>
<body class="bg-light">
  <!--AQUI ESTA EL NAVBAR SOLO HAGAN EXTENDS A BASE.HTML Y YA TIENEN TODO-->


      <!-- Navbar -->
      <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
          <a
              class="btn btn-dark px-3"
              href="/"
              role="button"
              ><i class="fa fa-book" aria-hidden="true"></i></a>

          <form class="d-flex" action="{{url_for('views.buscar')}}" method="post">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="titulo">
            <button class="btn btn-outline-success" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
          </form>

          <div class="d-flex align-items-center">
            {% if user.is_authenticated %}
              <a
              class="btn btn-light px-2"
              href="#"
              role="button"
              href="\seguimiento"
              ><i class="fa fa-shopping-cart" aria-hidden="true"></i>
              </a>
              <a
                class="btn btn-light px-2"
                href="#"
                role="button"
                href="#"
                ><i class="fa fa-user" aria-hidden="true"></i>
              </a>

              <a class="nav-item nav-link" id="logout" href="/logout">
                <button type="button" class="btn btn-primary me-3" ">Logout</button>
              </a>


            {% else %}

              <a class="nav-item nav-link" id="login" href="/login">
                <button type="button" class="btn btn-link px-3 me-2">Login</button>
              </a>
              <a class="nav-item nav-link" id="signUp" href="/sign-up">
                <button type="button" class="btn btn-primary me-3">Sign up</button>
              </a>
              <a class="nav-item nav-link" id="seguimiento" href="/seguimiento">
                <button type="button" class="btn btn-primary me-3">Seguimiento</button>
              </a>

            {% endif %}
              <a href="{{url_for('views.carritoCompras')}}" class="btn btn-primary">
                <i class="fas fa-shopping-cart"></i> Carrito
              </a>
          </div>
        </div>
      </nav>
      <!-- Navbar -->
      <!-- ESTA ES UNA SEPARACION ENTRE EL NAVBAR Y LOS ALERTS-->

      <!-- Este pedazo de codigo es solo para habilitar mensajes de error o alerts y flashs -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages%}
      {% if category =='error' %}
      <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% else %}
      <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %}
      {% endfor %}
      {% endif %}
      {% endwith %}
      <!-- Aqui en este div se pone las cosas que cambian en la pagina -->
      <div class="container">
        {% block content %}{% endblock %}
      </div>

      <!-- Aqui se importan todos los js que se necesiten-->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
    ></script>
    <script
        src="https://code.jquery.com/jquery-3.7.1.slim.js"
        integrity="sha256-UgvvN8vBkgO0luPSUl2s8TIlOSYRoGFAX4jlCIm9Adc="
        crossorigin="anonymous"
    ></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"
        integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"
    ></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script
        type="text/javascript"
        src="{{ url_for('static',filename='index.js')}}"
    ></script>
    {% block script %}{% endblock %}
    <!-- AQUI VA EL FOOTER-->
    <footer class="bg-dark text-center text-white">
      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2023 Copyright:
        <a class="text-white" href="#">Amazon 2.0</a>
      </div>
      <!-- Copyright -->
    </footer>

  
</body>
</html>

website/templates/buscar.html
{% extends "base.html" %}

{% block title %}
Resultados de búsqueda
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        {% for libro in libros %}
        <div class="col-2 mb-4">
            <a href="{{ url_for('views.detalle', id_libro=libro.id) }}" class="card-link d-block">
                <div class="card card-square">
                    <img src="{{ libro.Imagen }}" class="card-img-top" alt="Imagen del libro {{ libro.titulo }}">
                    <div class="card-body">
                        <h6 class="card-title text-center">{{ libro.titulo }}</h6>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}
{% block link %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
<style>
    .pagination-container {
        background-color: #f7f7f9;
        padding: 15px;
        border-radius: 8px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }
.card-square {
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    transition: transform 0.2s;
    overflow: hidden;
}

.card-square:hover {
    transform: scale(1.05);
}

.card-img-top {
    height: 250px;
    object-fit: cover;
}

.card-body {
    background-color: #f8f8f8;
}

.card-title {
    margin-bottom: 0.5rem;
}

.card-link {
    text-decoration: none;
    color: inherit;
}



</style>
{% endblock %}
{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Lo mas reciente</h1>

    <!-- Primera fila con 5 tarjetas -->
<div class="row">
    {% for libro in libros %}
    <div class="col-2 mb-4">
        <a href="{{ url_for('views.detalle', id_libro=libro.id) }}" class="card-link">
            <div class="card card-square">
                <img src="{{ libro.Imagen}}" class="card-img-top" alt="Imagen del libro {{ libro.titulo }}">
                <div class="card-body">
                    <h6 class="card-title text-center">{{ libro.titulo }}</h6>
                    <h6 class="card-title text-center">${{ libro.precio }}</h6>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Barra de Paginación con Bootstrap Ampliada</title>
    <!-- Añade el CDN de Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .pagination-container {
            background-color: #f7f7f9; /* Color de fondo */
            padding: 15px; /* Espacio alrededor */
            border-radius: 8px; /* Bordes redondeados */
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1); /* Sombra ligera */
        }
    </style>
</head>
<body>
<!--paginacion-->
<div class="container mt-5 d-flex justify-content-center">
    <div class="pagination-container">
        <ul class="pagination mb-0">
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Anterior</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">3 <span class="sr-only">(actual)</span></a>
            </li>
            <li class="page-item"><a class="page-link" href="#">4</a></li>
            <li class="page-item"><a class="page-link" href="#">5</a></li>
            <li class="page-item">
                <span class="page-link">...</span>
            </li>
            <li class="page-item"><a class="page-link" href="#">50</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Siguiente</a>
            </li>
        </ul>
    </div>
</div>

<!-- Añade los scripts de Bootstrap y jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}
{% block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        placeholder="Enter password"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
  </form>
{% endblock %}

website/templates/pagos.html
{% extends "base.html" %}

{% block title %}
Pago
{% endblock %}

{% block link %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
<style>
.cart-container {
    background-color: #f7f7f9;
    padding: 30px;
    border-radius: 10px;
    box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.1);
}

.cart-header {
    color: #333;
    border-bottom: 2px solid #e0e0e0;
    margin-bottom: 25px;
    padding-bottom: 10px;
}

.table {
    background-color: #ffffff;
    border-radius: 5px;
    overflow: hidden;  /* Para respetar el border-radius en thead */
}

.table thead th {
    background-color: #4e4e70;  /* Un color más suave para el header */
    color: #ffffff;
}

.table tbody tr:hover {
    background-color: #f2f2f2;  /* Color al pasar el mouse sobre una fila */
}

.btn-danger {
    border: none;  /* Remover borde */
}

.btn-danger:hover {
    opacity: 0.8;  /* Efecto al pasar el mouse sobre el botón */
}

        .image-option {
            display: block;
            cursor: pointer;
            border: 3px solid transparent; /* Borde transparente por defecto */
            border-radius: 5px;
            transition: border 0.3s ease, box-shadow 0.3s ease; /* Agregamos una transición para box-shadow */
            padding: 5px; /* Añadimos un padding */
        }

        .image-option:hover {
            border: 3px solid #d2d6de; /* Borde sutil cuando se pasa el mouse por encima */
        }

        .image-option img {
            width: 90px;
            height: 90px;
            object-fit: cover;
            border-radius: 2px;
        }

        /* Cuando el radio button esté seleccionado, aplicamos los estilos a la etiqueta siguiente */
        input[type="radio"]:checked + .image-option {
            border: 3px solid #007BFF; /* Borde más grueso cuando está seleccionado */
            box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.2); /* Sombra suave alrededor de la etiqueta seleccionada */
        }

</style>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="cart-container">
        <h2 class="cart-header">Carrito de Compras</h2>
        <table class="table table-bordered table-hover">
            <thead class="thead-dark">
            <tr>
                <th>Artículo</th>
                <!-- <th>Imagen</th> -->
                <th>Cantidad</th>
                <th>Precio Unitario</th>
                <th>Precio Total</th>
                <th>Acción</th>
            </tr>
            </thead>
            <tbody>
            <!-- Ejemplo de una fila -->
            <tr>
                <td>Nombre del producto 1</td>
                <!--<td><img src="URL_IMAGEN" alt="Nombre del producto 1" width="50"></td>-->
                <td>2</td>
                <td>$10</td>
                <td>$20</td>
                <td><button class="btn btn-danger btn-sm"><i class="fas fa-trash-alt"></i> Eliminar</button></td> <!-- Ícono de Font Awesome para la acción de eliminar -->
            </tr>
            <!-- Puedes añadir más filas siguiendo el mismo patrón -->
            </tbody>
        </table>
    </div>
</div>


<!-- Botón para abrir el modal -->
<div class="d-flex justify-content-center">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#formularioModal">
        Pagar
    </button>
</div>

<!-- El modal en sí -->
<div class="modal fade" id="formularioModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Cabecera del modal -->
            <div class="modal-header">
                <h4 class="modal-title">Formulario de Pago</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Cuerpo del modal con las pestañas y el formulario -->
            <div class="modal-body">
                <ul class="nav nav-tabs" id="myTabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="tarjeta-tab" data-toggle="tab" href="#tarjeta" role="tab">Tarjeta de Crédito/Débito</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="cheque-tab" data-toggle="tab" href="#cheque" role="tab">Cheque</a>
                    </li>
                </ul>

                <div class="tab-content mt-3" id="myTabsContent">
                    <!-- Pestaña de Tarjeta de Crédito/Débito -->
                    <div class="tab-pane fade show active" id="tarjeta" role="tabpanel">
                        <form action="{{ url_for('views.pagar') }}" method="post">
                            <div class="form-group">
                                <label for="nombreTitularTarjeta">Nombre del titular</label>
                                <input type="text" class="form-control" id="nombreTitularTarjeta" name="nombreTitularTarjeta" placeholder="Tal como aparece en la tarjeta">
                            </div>
                            <div class="form-group">
                                <label for="numeroTarjeta">Número de la tarjeta</label>
                                <input type="text" class="form-control" id="numeroTarjeta" name="numeroTarjeta" placeholder="Ej. 1234 5678 1234 5678">
                            </div>
                            <div class="form-group">
                                <label for="fechaVencimiento">Fecha de vencimiento</label>
                                <input type="text" class="form-control" id="fechaVencimiento" name="fechaVencimiento" placeholder="MM/AA">
                            </div>
                            <div class="form-group">
                                <label for="cvv">Código de seguridad (CVV/CVC)</label>
                                <input type="text" class="form-control" id="cvv" name="cvv" placeholder="Ej. 123">
                            </div>
                            <div class="form-group">
                                <label for="direccionFacturacion">Dirección de facturación</label>
                                <input type="text" class="form-control" id="direccionFacturacion" name="direccionFacturacion">
                            </div>
                            <div class="form-group">
                                <label for="tipoTarjeta">Tipo de tarjeta</label>
                                <select class="form-control" id="tipoTarjeta" name="tipoTarjeta">
                                    <option>Visa</option>
                                    <option>MasterCard</option>
                                    <option>American Express</option>
                                </select>
                            </div>
                            <div class="container mt-5">
                                    Paqueteria
                                    <form action="tu_ruta_de_procesamiento" method="post">
                                        <div class="row justify-content-center"> <!-- Centrado de los items -->

                                            <!-- Opción 1 -->
                                            <div class="col-auto">
                                                <input type="radio" id="opcion1" name="paqueteria" value="opcion1" />
                                                <label for="opcion1" class="image-option m-2">
                                                    <img src="https://www.dhl.com/content/dam/dhl/global/core/images/teaser-image-main/dhl-logo.jpg" alt="Paquetería 1" class="img-fluid">
                                                </label>
                                            </div>

                                            <!-- Opción 2 -->
                                            <div class="col-auto">
                                                <input type="radio" id="opcion2" name="paqueteria" value="opcion2" />
                                                <label for="opcion2" class="image-option m-2">
                                                    <img src="https://lh3.googleusercontent.com/YtXTsa-6SaaMl02-OUo8iRztlX5Thu4aCLavunIV1M5hm9y4ySTPpMjpY44fL4ayz7Se" alt="Paquetería 2" class="img-fluid">
                                                </label>
                                            </div>

                                            <!-- Opción 3 -->
                                            <div class="col-auto">
                                                <input type="radio" id="opcion3" name="paqueteria" value="opcion3" />
                                                <label for="opcion3" class="image-option m-2">
                                                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/United_Parcel_Service_logo_2014.svg/1718px-United_Parcel_Service_logo_2014.svg.png" alt="Paquetería 3" class="img-fluid">
                                                </label>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                            <button type="submit" class="btn btn-primary mt-2">Pagar con Tarjeta</button>
                        </form>
                    </div>

                    <!-- Pestaña de Cheque -->
                    <div class="tab-pane fade" id="cheque" role="tabpanel">
                        <form action="{{ url_for('views.pagar') }}" method="post">
                            <div class="form-group">
                                <label for="nombreTitularCheque">Nombre del titular</label>
                                <input type="text" class="form-control" id="nombreTitularCheque" name="nombreTitularCheque">
                            </div>
                            <div class="form-group">
                                <label for="numeroCuenta">Número de cuenta</label>
                                <input type="text" class="form-control" id="numeroCuenta" name="numeroCuenta">
                            </div>
                            <div class="form-group">
                                <label for="numeroRuta">Número de ruta del banco</label>
                                <input type="text" class="form-control" id="numeroRuta" name="numeroRuta">
                            </div>
                            <div class="form-group">
                                <label for="direccionTitular">Dirección del titular</label>
                                <input type="text" class="form-control" id="direccionTitular" name="direccionTitular">
                            </div>
                            <div class="form-group">
                                <label for="numeroCheque">Número de cheque</label>
                                <input type="text" class="form-control" id="numeroCheque" name="numeroCheque">
                            </div>
                            <div class="form-group">
                                <label for="cantidad">Cantidad</label>
                                <input type="number" class="form-control" id="cantidad" name="cantidad" step="0.01">
                            </div>
                            <div class="container mt-5">
                                    Paqueteria
                                    <form action="tu_ruta_de_procesamiento" method="post">
                                        <div class="row justify-content-center"> <!-- Centrado de los items -->

                                            <!-- Opción 1 -->
                                            <div class="col-auto">
                                                <input type="radio" id="opcion1" name="paqueteria" value="opcion1" />
                                                <label for="opcion1" class="image-option m-2">
                                                    <img src="https://www.dhl.com/content/dam/dhl/global/core/images/teaser-image-main/dhl-logo.jpg" alt="Paquetería 1" class="img-fluid">
                                                </label>
                                            </div>

                                            <!-- Opción 2 -->
                                            <div class="col-auto">
                                                <input type="radio" id="opcion2" name="paqueteria" value="opcion2" />
                                                <label for="opcion2" class="image-option m-2">
                                                    <img src="https://lh3.googleusercontent.com/YtXTsa-6SaaMl02-OUo8iRztlX5Thu4aCLavunIV1M5hm9y4ySTPpMjpY44fL4ayz7Se" alt="Paquetería 2" class="img-fluid">
                                                </label>
                                            </div>

                                            <!-- Opción 3 -->
                                            <div class="col-auto">
                                                <input type="radio" id="opcion3" name="paqueteria" value="opcion3" />
                                                <label for="opcion3" class="image-option m-2">
                                                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/United_Parcel_Service_logo_2014.svg/1718px-United_Parcel_Service_logo_2014.svg.png" alt="Paquetería 3" class="img-fluid">
                                                </label>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            <button type="submit" class="btn btn-primary mt-2">Pagar con Cheque</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}